# Imports

In [1]:
import tensorflow as tf
import numpy as np
from PIL import Image
import matplotlib.image as mti

# Reading The Image

We read the image then we transpose it inorder to get the right shape

In [2]:
img = Image.open("Fire.jpg")
array = tf.keras.preprocessing.image.img_to_array(img)
array = array.T
array.shape

(3, 2560, 1920)

In [3]:
array

array([[[ 0.,  0.,  0., ...,  2.,  1.,  1.],
        [ 0.,  0.,  0., ...,  2.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        ...,
        [ 0.,  0.,  0., ...,  4.,  6.,  7.],
        [ 0.,  0.,  0., ...,  4.,  6.,  8.],
        [ 0.,  0.,  0., ...,  4.,  6.,  8.]],

       [[ 0.,  0.,  0., ...,  2.,  1.,  1.],
        [ 0.,  0.,  0., ...,  2.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        ...,
        [ 0.,  0.,  0., ...,  6.,  8.,  9.],
        [ 0.,  0.,  0., ...,  6.,  8., 10.],
        [ 0.,  0.,  0., ...,  6.,  8., 10.]],

       [[ 0.,  0.,  0., ...,  2.,  1.,  1.],
        [ 0.,  0.,  0., ...,  2.,  1.,  1.],
        [ 0.,  0.,  0., ...,  1.,  1.,  1.],
        ...,
        [ 0.,  0.,  0., ...,  5.,  7.,  8.],
        [ 0.,  0.,  0., ...,  5.,  7.,  9.],
        [ 0.,  0.,  0., ...,  5.,  7.,  9.]]], dtype=float32)

# Choice 

we notice that the array is a tensor of order 3, it contains 3 matrices of 2560x1920 which is the resolution of the image.
We choose one of them to perform the requested tasks.we will go with the first matrice ( index 0 ).

In [4]:
subArray = array[0]
subArray

array([[0., 0., 0., ..., 2., 1., 1.],
       [0., 0., 0., ..., 2., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 4., 6., 7.],
       [0., 0., 0., ..., 4., 6., 8.],
       [0., 0., 0., ..., 4., 6., 8.]], dtype=float32)

# 1) - Transposition

In [5]:
transSubArray = subArray.T
transSubArray

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [2., 2., 1., ..., 4., 4., 4.],
       [1., 1., 1., ..., 6., 6., 6.],
       [1., 1., 1., ..., 7., 8., 8.]], dtype=float32)

# 2) - Special Matrix Check

## 2.1) - Diagonal

In [6]:
def isDiag(M):
    return np.allclose(M,np.diag(M))

isDiag(subArray)

False

## 2.2) - U Trian

In [7]:
def isUT(M):
    return np.allclose(M,np.triu(M))

isUT(subArray)

False

## 2.3) - L Trian

In [8]:
def isLT(M):
    return np.allclose(M,np.tril(M))

isLT(subArray)

False

## 2.4) - Identity

In [9]:
def isI(M):
    return (M.shape[0]==M.shape[1]) and (np.allclose(M,np.identity(M.shape[0])))

isI(subArray)

False

# 3) - Norms

In [10]:
from numpy.linalg import norm
c = subArray.T[0] # to get the colmun and not the line
c

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

## L1

In [11]:
norm_l1 = norm(c, 1)
norm_l1

8450.0

## L2

In [12]:
norm_l2 = norm(c)
norm_l2

276.1304